files:
  "/opt/elasticbeanstalk/hooks/appdeploy/post/99_make_storage_writable.sh":
    mode: "000755"
    owner: root
    group: root
    content: |
      #!/usr/bin/env bash
      chown nodejs:nodejs /tmp/deployment/application/node_modules/
      chown nodejs:nodejs /tmp/.npm
      chmod -R 755 /tmp/deployment/application/node_modules/
      chmod -R 755 /tmp/.npm
packages:
  yum:
    gcc: []
    make: []
    openssl-devel: []
    libxml2: []
    libxml2-devel: []
    gcc-c++: []
branch-defaults:
  master:
    environment: chain-rx
global:
  application_name: chain-rx
  default_ec2_keyname: chainrx-dev
  default_platform: 64bit Amazon Linux 2018.03 v4.5.0 running Node.js
  default_region: us-east-1
  sc: git
  profile: eb-cli